# Generated by Django 2.0.7 on 2018-07-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0004_auto_20180718_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
    ]
